### ISSUE TITLE
Change Existing Console to work with Global Console

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2424]
#2408 describes a Global Console that will allow a user of EnMasse to manage all the addressspaces within a cluster.   Eventually, the functionality offered today by the Existing Console will be migrated to the new Global Console, but for the first phase, the Global Console will link the user through to the Console to manage the contents of the address space. 

There are a number of areas of the Existing Console that need to be changed to allow it to work with the Global Console.  We will endeavour to minimise the changes to the Existing Console in recognition of the fact that we desire to retire it in the near term.  We won't be rearchitecting it!

GC = Global Console
ASC = Address Space Console (the Existing Console)

### Replace authentication backend from using Keycloak to use OAuth2 directly.

This allows for a single sign-on experience between the GC and ASC.  Currently in order to use the ASC the user must authenticate with a federated user (that is known to the addressspace).   This model doesn't work when a single logged on user need to manage multiple addressspaces. The requirement for a federated user will be removed.  

The ASC will integrate directly with OAuth2.    It will accept the OAuth Endpoint URI as configuration items.  When deployed on OpenShift, these OAuth Endpoint URIs will refer to an `oauthclient` laid down by EnMasse operator during install. On Kubernettes the user will be providing their own OpenID Connect capable OAUTH2 server (https://kubernetes.io/docs/reference/access-authn-authz/authentication/).   The OAuth Endpoint URIs will refer to this deployment.

### Authorisation decisions based on Kubernettes RBAC rather than Keycloak groups

Currently the console-server looks-up the user's groups from Keycloak are uses this information to access to the address space as a whole, the viewing of addresses within an addressspace, and the permissioning of the creation/deletion of addresses.   Kubernettes RBAC do not play a part (the console-server runs under a service account with sufficient privileges to perform actions on behalf of the user, but Kubernettes itself its not aware of the user).

This will be changed so that [Kubernettes RBAC](https://kubernetes.io/docs/reference/access-authn-authz/authorization/) is used for exclusively for permission.

#### Authentication / Authorisation

The client side application will be responsible for initiating the OAuth2 authentication.  If the user has arrived at the ASC from the GC, no there SSO session will continue and there will be no login workflow.   

The console-server requires the bearer token in order to act of the user's behalf.   We will pass the bearer token over to the server side over the client to server AMQP-WS connection.

#### Console Gateway permission

Currently the console-server performs an authorisation check that ensures that the user has `io.enmasse.user.model.v1.Operation#manage` or the user has any address view permission. If the user holds either permission, they are granted access to the Console.  This decision point with by replace with a check for `GET` permission on the `AddressSpace` resource in question. 

#### Create/Delete Address

Currently the console-server performs an authorisation check that ensures that the user has `Operation#manage`.    The console-server will be changed to invoke the API operations with the user's token.  This will of course delegate the authorisation check down to normal RBAC.

#### View Address

Currently the console-server learns of all address by watching the config-map of type address-config (performing the operation as the service account).  Before feeding the address results to the connected UI users, if filters those addresses to which the user has no entitlement to see based on whether the user possess `Operation#manage` or has a matching view permission for the address in question. 

The desire is to show to the user only address that they have GET RBAC permission.

The console-server will need to change to ensure that only addresses that the user has GET RBAC on are sent to the user.  To implement this with *least* change, the console-server will need to perform an additional API GET address as it becomes aware of new address for every connected user and use this this information to filter the result sets.  It could cache the result of the GET to avoid a excessive load.

A better approach would be a deeper refactoring. console-server (kubernetes.js) would perform a separate config map GET/watch on behalf of each connected user.  The console-server would then need to apply the statistics to the separate user-owned results set rather than the single master set it holds today.  The user owned results set changes would be fed back over the wireto the console-UI.   

### Gathering of Statistics From Routers and Brokers

No changes required - the console server continues to authenticate to these resources as it does today.

### Navigation back from Address Space Console to the Global Console.

If the GC is available, there must be a back link that take the user from the ASC to the GC. 

### Reskin the Address Space Console to give it PatternFly 4 look and feel.

https://github.com/patternfly/patternfly-next/pull/1467 might hold some clues!

### Task List

- [ ] Replace authentication provider from using keycloak to use OAuth2 directly.
- [ ] Console-server authorisation decisions based on Kubernettes RBAC rather than Keycloak groups
- [ ] Navigation back from Address Space Console to the Global Console.
- [ ] Reskin the Address Space Console to give it PatternFly 4 look and feel.
- [ ] Refactor tests and documentation.
 

### Other considerations/questions

This would be a breaking change for users. Existing operator would need to be permissioned with appropriate RBAC permissions.

How would permission for objects that aren't represented at Kubernettes level be represented?  For instance a permission to be allowed to purge queue?

**Comment by k-wall** [comment]
One issue:  when an addressspace is created and the ASC is deployed, will the address-space-controller have sufficient rights to update the [OAuthClient](https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authentication.html#oauth-clients) that was deployed by install operator?  If no, then this creates a issue for a user who bookmarks an ASC hyperlink.   On navigating to that link, they will be redirected through login and then ideally be directed back to the ASC URL, however, the OAuthClient won't be know the ASC URL as a valid redirect URL, so the redirect will be rejected by the OAuth provider.  One solution would be redirect back to the global console and a have special query arguments that direct the redirect the browser again to the desired ASC.

**Comment by k-wall** [comment]
Closed by #2581
